use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=kernels");

    let kernels_dir = Path::new("kernels");
    let out_dir_str = env::var("OUT_DIR").unwrap();
    let out_dir = Path::new(&out_dir_str);

    // Create kernels.ptx.rs file that will contain constants for each kernel
    let ptx_rs_content = String::from("// Auto-generated by build.rs\n\n");

    // Find all .cu files in the kernels directory
    let cu_files = fs::read_dir(kernels_dir)
        .expect("Failed to read kernels directory")
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry
                .path()
                .extension()
                .map(|ext| ext == "cu")
                .unwrap_or(false)
        });

    // Compile each .cu file to .ptx
    for cu_file in cu_files {
        let cu_path = cu_file.path();
        let ptx_name = cu_path
            .file_stem()
            .unwrap()
            .to_str()
            .unwrap()
            .to_string() + ".ptx";
        let ptx_path = out_dir.join(&ptx_name);

        println!("cargo:warning=Compiling CUDA kernel: {:?}", cu_path);

        // Find VS 2019 Build Tools compiler
        let compiler_bindir = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64";

        let output = Command::new("nvcc")
            .arg("-ptx")
            .arg(&cu_path)
            .arg("-o")
            .arg(&ptx_path)
            .arg("--compiler-bindir")
            .arg(compiler_bindir)
            .output();

        match output {
            Ok(o) if o.status.success() => {
                println!("cargo:warning=Successfully compiled {:?}", cu_path);
            }
            Ok(o) => {
                let stderr = String::from_utf8_lossy(&o.stderr);
                panic!(
                    "nvcc failed to compile {:?}:\n{}",
                    cu_path,
                    stderr
                );
            }
            Err(e) => {
                panic!("Failed to execute nvcc: {}. Ensure CUDA toolkit is installed and nvcc is in PATH", e);
            }
        }

        // Tell cargo to rerun if the .cu file changes
        println!("cargo:rerun-if-changed={}", cu_path.display());
    }

    // Write the kernels.ptx.rs file
    let ptx_rs_path = out_dir.join("kernels.ptx.rs");
    fs::write(&ptx_rs_path, ptx_rs_content)
        .expect("Failed to write kernels.ptx.rs");
}
